name: GH Actions Cron Schedule
on:
  workflow_dispatch:
  schedule:
    # Every M-F at 12:00am run this job
    - cron:  "0 0 * * 1-5"
    
jobs:
  check-image-version:
    uses: tommyd450/actions/.github/workflows/check-image-version.yaml@main
    strategy:
      matrix:
        branch: [main, redhat-v0.8]
    with:
      branch: ${{ matrix.branch }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      REDHAT_REGISTRY_USERNAME: ${{ secrets.REDHAT_REGISTRY_USERNAME }}
      REDHAT_REGISTRY_PASSWORD: ${{ secrets.REDHAT_REGISTRY_PASSWORD }}